FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app
COPY / ./

RUN dotnet format /app/backend/src/api/API/API.csproj --verify-no-changes &&\
    dotnet publish /app/backend/src/api/API/API.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

RUN apt-get update &&\
    apt-get install -y curl libicu-dev &&\
    rm -rf /var/lib/apt/lists/*

COPY --from=build /out ./

ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "API.dll"]